services:
  postgres:
    image: postgres:16
    container_name: meal_planner_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: meal_planner_user
      POSTGRES_PASSWORD: meal_planner_password
      POSTGRES_DB: meal_planner_db
    ports:
      - "5432:5432"
    volumes:
      - meal_planner_postgres_data:/var/lib/postgresql/data

volumes:
  meal_planner_postgres_data: